ishuhui/models/chapter.py
from ishuhui.extensions.flasksqlalchemy import db
import ishuhui.data


class Chapter(db.Model):
    __tablename__ = 'chapters'
    id = db.Column(db.Integer, primary_key=True, unique=True)
    title = db.Column(db.String(256), nullable=False)
    comic_id = db.Column(db.Integer, nullable=False)
    chapter_number = db.Column(db.Integer, nullable=False)
    front_cover = db.Column(db.String(256), nullable=True)
    refresh_time = db.Column(db.DateTime, nullable=True)
    images = db.Column(db.Text, nullable=True)

    def comic(self):
        return ishuhui.data.get_comic(self.comic_id)

ishuhui/models/comic.py
from ishuhui.extensions.flasksqlalchemy import db


class Comic(db.Model):
    __tablename__ = 'comics'
    id = db.Column(db.Integer, primary_key=True, unique=True)
    title = db.Column(db.String(256), nullable=False)
    description = db.Column(db.String(1024), nullable=False)
    refresh_time = db.Column(db.DateTime, nullable=True)
    author = db.Column(db.String(256), nullable=True)
    classify_id = db.Column(db.Integer, nullable=False)
    front_cover = db.Column(db.String(256), nullable=True)

ishuhui/__init__.py
from flask import Flask


def create_app(config):
    app = Flask(__name__)
    app.config.from_object(config)
    app.config.from_envvar('FLASKR_SETTINGS', silent=True)
    from ishuhui.extensions.flasksqlalchemy import db
    db.init_app(app)

    from ishuhui.logger import init_logger
    init_logger(app)

    from ishuhui.controllers.comic import bp_comic
    app.register_blueprint(bp_comic)

    from ishuhui.controllers.admin import bp_admin
    app.register_blueprint(bp_admin)

    from ishuhui.controllers.error import bp_error
    app.register_blueprint(bp_error)

    from ishuhui.schedulers.scheduler import init_scheduler
    init_scheduler(app)

    with app.app_context():
        db.create_all()
    return app

ishuhui/controllers/admin.py
from flask import Blueprint
from flask import current_app, request, abort, jsonify

import ishuhui.tasks.task as task

bp_admin = Blueprint('admin', __name__, url_prefix='/admin')


def login():
    if current_app.config['USERNAME'] != request.args.get('username') or current_app.config['PASSWORD'] != request.args.get('password'):
        abort(404)


bp_admin.before_request(login)


@bp_admin.route('/refresh_comics')
def refresh_comics():
    return jsonify(task.refresh_comics())


@bp_admin.route('/refresh_chapters')
def refresh_chapters():
    return jsonify(task.refresh_chapters())


@bp_admin.route('/refresh_comic_images')
def refresh_comic_images():
    return jsonify(task.refresh_comic_images())

ishuhui/controllers/comic.py
import re, requests
from flask import render_template, Blueprint, json, abort

import ishuhui.data as data
from ishuhui.extensions.flasksqlalchemy import db

bp_comic = Blueprint('comic', __name__)


@bp_comic.route('/')
def latest_chapters():
    chapters = data.get_latest_chapters(12)
    return render_template('latest.html', comic=None, chapters=chapters)


@bp_comic.route('/comics')
def comics():
    comics = data.get_comics()
    return render_template('comics.html', comics=comics)


@bp_comic.route('/comics/<int:comic_id>/chapters')
def chapters(comic_id):
    comic = data.get_comic(comic_id)
    chapters = data.get_chapters(comic_id)
    return render_template('chapters.html', comic=comic, chapters=chapters)


image_pattern = re.compile(r'<img [^>]*src="([^"]+)')


def get_images_from_url(url):
    html = requests.get(url).text
    images = image_pattern.findall(html)
    return images


@bp_comic.route('/refresh_chapters/<int:chapter_id>', methods=['GET'])
def refresh_chapter(chapter_id):
    chapter = data.get_chapter(chapter_id)
    url = 'http://www.ishuhui.net/ComicBooks/ReadComicBooksToIsoV1/' + str(
        chapter_id) + '.html'
    images = get_images_from_url(url)
    chapter.images = json.dumps(images)
    db.session.commit()
    return json.dumps(images)


@bp_comic.route('/comics/<int:comic_id>/chapters/<int:chapter_id>')
def chapter(comic_id, chapter_id):
    comic = data.get_comic(comic_id)
    chapter = data.get_chapter(chapter_id)
    next_chapter = data.get_next_chapter(comic_id, chapter.chapter_number)
    prev_chapter = data.get_prev_chapter(comic_id, chapter.chapter_number)
    url = 'http://www.ishuhui.net/ComicBooks/ReadComicBooksToIsoV1/' + str(
        chapter_id) + '.html'
    if chapter.comic_id != comic_id:
        abort(404)
    if chapter.images:
        images = json.loads(chapter.images)
    else:
        images = get_images_from_url(url)
        chapter.images = json.dumps(images)
        db.session.commit()
    return render_template(
        'images.html',
        comic=comic,
        chapter=chapter,
        next_chapter=next_chapter,
        prev_chapter=prev_chapter,
        images=images,
        url=url)

ishuhui/controllers/error.py
from flask import render_template, Blueprint

bp_error = Blueprint('error', __name__, template_folder="../templates/error")


@bp_error.app_errorhandler(404)
def page_not_found(error):
    return render_template('error.html', error=error)


@bp_error.app_errorhandler(500)
def server_error(error):
    return render_template('error.html', error=error)

ishuhui/data/__init__.py
from ishuhui.models.chapter import Chapter
from ishuhui.models.comic import Comic
from sqlalchemy import and_


def get_comics():
    return Comic.query.all()


def get_comic(comic_id):
    return Comic.query.get(comic_id)


def get_chapters(comic_id=None):
    if comic_id is None:
        return Chapter.query.order_by(Chapter.chapter_number.desc()).all()
    return Chapter.query.filter_by(comic_id=comic_id).order_by(Chapter.chapter_number.desc()).all()


def get_next_chapter(comic_id, chapter_number):
    chapter = Chapter.query.filter(
        and_(Chapter.comic_id == comic_id, Chapter.chapter_number > chapter_number)).order_by(
        Chapter.chapter_number.asc()).first()
    return chapter


def get_prev_chapter(comic_id, chapter_number):
    chapter = Chapter.query.filter(
        and_(Chapter.comic_id == comic_id, Chapter.chapter_number < chapter_number)).order_by(
        Chapter.chapter_number.desc()).first()
    return chapter


def get_chapter(chapter_id):
    return Chapter.query.get(chapter_id)


def get_latest_chapters(cnt=10):
    return Chapter.query.order_by(Chapter.refresh_time.desc()).limit(cnt).all()

ishuhui/logger/__init__.py
import logging
from logging.handlers import RotatingFileHandler


def init_logger(app):
    handler = RotatingFileHandler('logs/ishuhui.log', maxBytes=1024 * 1024 * 2, backupCount=2)
    logging_format = logging.Formatter(
        '%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]')
    handler.setFormatter(logging_format)
    app.logger.addHandler(handler)
    app.logger.setLevel(logging.INFO)

ishuhui/templates/chapters.html
{% extends "layout.html" %}
{% block title %}{{ comic.title }}{% endblock %}
{% block content %}
    {% include 'navbar.html' %}
    <div class="mt-3">
        <div class="card mdui-card" style="margin-bottom:1rem;">
            <div style="height: 7rem; background:url('{{ comic.front_cover }}') no-repeat center center; background-size: cover;">
            </div>
            <div class="card-body">
                <h3 class="card-title">{{ comic.title }}</h3>
                <p class="card-text">{{ comic.description }}</p>
            </div>
        </div>
        <div id="chapters">
            <input type="search" class="search mb-3 form-control form-control-lg"
                   placeholder="Search for title or chapter number from {{ chapters|length }} chapters.">
            <div class="row" data-masonry='{ "itemSelector": ".col", "columnWidth":".col" }'>
                {% for chapter in chapters %}
                    <div class="col col-xs-6 col-sm-4 col-md-3 col-lg-2 mb-3">
                        <div class="card mdui-card mdui-hoverable">
                            <div class="card-body">
                                <h6 class="card-title title">{{ chapter.title }}</h6>
                                <footer>
                                    <p class="card-text">
                                        <small class="text-muted chapter_number">第{{ chapter.chapter_number }}话</small>
                                    </p>
                                    <a href="{{ url_for('comic.chapter', comic_id=chapter.comic_id, chapter_id=chapter.id) }}"
                                       class="btn btn-sm btn-primary">View</a>
                                </footer>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}
{% block footer %}
    {{ super() }}
    <script>
        var options = {
            valueNames: ['title', 'chapter_number'],
            listClass: 'row'
        };
        var list = new List('chapters', options);
        list.on('updated', function () {
            $('.row').masonry();
        })
    </script>
{% endblock %}

ishuhui/templates/comics.html
{% extends "layout.html" %}
{% block title %}所有{% endblock %}
{% block content %}
    {% include 'navbar.html' %}
    <div class="mt-3">
        <div id="comics">
            <input type="search" class="search mb-3 form-control form-control-lg"
                   placeholder="Search from {{ comics|length }} comics.">
            <div class="row" data-masonry='{ "itemSelector": ".col", "columnWidth":".col" }'>
                {% for comic in comics %}
                    <div class="col col-xs-12 col-sm-6 col-md-4 col-lg-4 col-xl-3 mb-3">
                        <div class="card mdui-card mdui-hoverable">
                            <img class="card-img-top" src="{{ comic.front_cover }}">
                            <div class="card-body">
                                <h4 class="title card-title">{{ comic.title }}</h4>
                                <p class="description card-text">{{ comic.description }}
                                    {% if comic.author %}
                                        <small class="text-muted"><em> -- {{ comic.author }}</em></small>
                                    {% endif %}
                                </p>
                                <footer>
                                    <p class="card-text">
                                        <small class="refresh_time text-muted">{{ comic.refresh_time }}</small>
                                    </p>
                                    <a href="{{ url_for('comic.chapters', comic_id=comic.id) }}"
                                       class="btn btn-primary btn-sm">View</a>
                                </footer>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %} {% block footer %} {{ super() }}
    <script>
        var options = {
            valueNames: ['title', 'description'],
            listClass: 'row'
        };
        var list = new List('comics', options);
        list.on('updated', function () {
            $('.row').masonry();
        });

        $('.row').imagesLoaded().progress(function () {
            $('.row').masonry();
        });
    </script>
{% endblock %}

ishuhui/templates/error.html
{% extends "layout.html" %} {% block content %}
    <div class="mt-3">
        <div class="alert alert-danger" role="alert">
            <p>
                <strong>ERROR: </strong>{{ error }}.
            </p>
            <hr>
            <p class="mb-0">Go <a class="alert-link" href="/">Home.</a></p>
        </div>
    </div>
{% endblock %}

ishuhui/templates/images.html
{% extends "layout.html" %}
{% block head %}
{{ super() }}
<link href="https://cdn.bootcss.com/lightgallery/1.6.0/css/lightgallery.min.css" rel="stylesheet">
{% endblock %}
{% block title %}{{ comic.title }}{{ chapter.chapter_number }}-{{ chapter.title }}{% endblock %}
{% block content %}
    <div class="row justify-content-center">
        <div class="mt-3 col-md-8">
            <ol class="breadcrumb" id="top">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item"><a
                        href="{{ url_for('comic.chapters', comic_id=comic.id) }}">{{ comic.title }}</a>
                </li>
                <li class="breadcrumb-item active">第{{ chapter.chapter_number }}话--<strong>{{ chapter.title }}</strong></li>
            </ol>
    
            <div class="card mdui-card" id="images">
                <div class="card-header">
                        {% if prev_chapter %}
                            <a class="float-left"
                                href="{{ url_for('comic.chapter', comic_id=comic.id, chapter_id=prev_chapter.id) }}">Prev({{ prev_chapter.title }})</a>
                        {% endif %}
                        {% if next_chapter %}
                            <a class="float-right"
                                href="{{ url_for('comic.chapter', comic_id=comic.id, chapter_id=next_chapter.id) }}">Next({{ next_chapter.title }})</a>
                        {% endif %}
                </div>
                <div>
                    {% for image in images %}
                        <div class="image" data-src="{{ image }}">
                            <img src="{{ image }}" class="img-fluid mb-1"
                            style="width:100%;display:block;">
                        </div>
                    {% endfor %}
                </div>
                <div class="card-footer">
                    {% if prev_chapter %}
                        <a class="float-left"
                           href="{{ url_for('comic.chapter', comic_id=comic.id, chapter_id=prev_chapter.id) }}">Prev({{ prev_chapter.title }})</a>
                    {% endif %}
                    {% if next_chapter %}
                        <a class="float-right"
                           href="{{ url_for('comic.chapter', comic_id=comic.id, chapter_id=next_chapter.id) }}">Next({{ next_chapter.title }})</a>
                    {% endif %}
                </div>
            </div>
            <a href="#top" class="mdui-fab mdui-fab-fixed mdui-ripple"><i class="mdui-icon material-icons">&#xe5d8;</i></a>
        </div>
    </div>
{% endblock %}
{% block footer %}
    {{ super() }}
    <script src="https://cdn.bootcss.com/lightgallery/1.6.0/js/lightgallery-all.min.js"></script>
    <script>
        var gallery = $("#images").lightGallery({
            selector: '.image',
            share: false,
            pause: 10000,
            closable: false,
            controls: false
        });
    </script>
{% endblock %}

ishuhui/templates/latest.html
{% extends "layout.html" %}
{% block title %}最新{% endblock %}
{% block content %}
    {% include 'navbar.html' %}
    <div class="mt-3">
        <div id="chapters">
            <div class="row" data-masonry='{ "itemSelector": ".col", "columnWidth":".col" }'>
                {% for chapter in chapters %}
                    {% set comic = chapter.comic() %}
                    <div class="col col-sm-6 col-md-4 mb-3">
                        <div class="card mdui-card mdui-card-hoverable text-white"
                             style="background: url('{{ chapter.front_cover }}') no-repeat center;background-size: cover">
                            <div class="card-body" style="background-color: rgba(33,33,33,0.6)">
                                <h3 class="card-title comic-title">{{ comic.title }}{{ chapter.chapter_number }}话</h3>
                                <h5 class="card-title chapter-title">{{ chapter.title }}</h5>
                                <p class="card-text comic-description">{{ comic.description }}</p>
                                <p class="card-text">
                                    <small>{{ chapter.refresh_time }}</small>
                                </p>
                                <a href="{{ url_for('comic.chapter', comic_id=chapter.comic_id, chapter_id=chapter.id) }}"
                                   class="btn btn-primary">View</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

ishuhui/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="utf-8">
        <meta name="referrer" content="never">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}{% endblock %} 漫画</title>
        <link href="//cdn.bootcss.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet">
        <link href="//cdn.bootcss.com/mdui/0.3.0/css/mdui.min.css" rel="stylesheet">
        <link href="{{ url_for('static', filename='style.css') }}" rel=stylesheet>
        <link rel="shortcut icon" href="https://static.lufficc.com/favicon.ico" />
    {% endblock %}
</head>

<body>
<div class="container">
    {% block content %}{% endblock %}
</div>
{% block footer %}
    <center class="mt-2 mb-2">&copy; Copyright 2017 By <a href="https://lufficc.com">lufficc</a>.</center>
    <script src="//cdn.bootcss.com/jquery/3.2.1/jquery.slim.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
    <script src="//cdn.bootcss.com/mdui/0.3.0/js/mdui.min.js"></script>
    <script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>
    <script src="//cdn.bootcss.com/masonry/4.2.0/masonry.pkgd.min.js"></script>
    <script src="//cdn.bootcss.com/list.js/1.5.0/list.min.js"></script>
{% endblock %}
</body>
</html>

ishuhui/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">
        <img src="https://i.loli.net/2017/08/26/59a15ddf9c36f.png" width="30" height="30"
             class="d-inline-block align-top"
             alt="">
        鼠绘漫画
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item{% if request.path=="/" %} active{% endif %}">
                <a class="nav-link" href="/">Latest <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item{% if request.path=="/comics" %} active{% endif %}">
                <a class="nav-link" href="{{ url_for('comic.comics') }}">All Comics</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://lufficc.com/">Blog</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://github.com/lufficc/flask_ishuhui.git">GitHub</a>
            </li>
        </ul>
    </div>
</nav>